name: VHDL CI (VUnit + GHDL)

on:
  push:
  pull_request:

jobs:
  vunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install GHDL
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository ppa:ghdl/ghdl
          sudo apt update
          sudo apt install -y ghdl-5.1.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt

      - name: Run VUnit tests
        run: python run.py --verbose 
